now account IDs get saved to and loaded from localStorage
NEARFoundation/tta-basic pull request #10
Opened 2022-11-29 20:44 UTC by ryancwalsh

https://near-foundation.atlassian.net/jira/software/c/projects/TTA/boards/5?modal=detail&selectedIssue=TTA-46

2022-11-30 14:11 UTC, PierreLeGuen requested changes

2022-11-30 14:11 UTC, PierreLeGuen commented on pages/index.tsx
> +    console.log('onChange', { accountIdsArray });
Remove console logs

2022-11-30 14:11 UTC, PierreLeGuen commented on pages/index.tsx
> +  // `accountIds` is an array instead of a Set so that users can temporarily paste multiple lines of the same account ID and then edit them to be unique before submitting the form. If they were a Set
Could we spread long comments on multiple lines?

2022-11-30 14:11 UTC, PierreLeGuen commented on helpers/localStorage.ts
> +      console.log(`Saving to localStorage key ${key}... 'valueToStore' = ${valueToStore}`);
Remove console log

2022-12-01 14:57 UTC, ryancwalsh commented on pages/index.tsx
> +  // `accountIds` is an array instead of a Set so that users can temporarily paste multiple lines of the same account ID and then edit them to be unique before submitting the form. If they were a Set
Yes. Done, and added an eslint rule to enforce it going forward.

2022-12-01 15:01 UTC, merged